---
name: presence-detector-example
# Example docker-compose file for HC-SR501 Presence Detector using Node-Red and MQTT with Node-Red
services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0.22
    container_name: mqtt-broker
    volumes:
      - ./config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - '0.0.0.0:1883:1883' # MQTT port
      - '0.0.0.0:9002:9001' # MQTT over WebSockets (optional, for MQTT over WebSocket support)
    networks:
      - IOT
    restart: unless-stopped

  node-red:
    image: nodered/node-red:4.1.6
    container_name: node-red
    depends_on:
      - mqtt-broker
    # network_mode: host
    volumes:
      - node_red_data:/data
    ports:
      - '0.0.0.0:1880:1880' # Map Node-RED's default port to the host
      - '0.0.0.0:3456:3456' # Alexa Config Port
    networks:
      - IOT
    restart: unless-stopped
    privileged: true

  portainer:
    image: portainer/portainer-ce:2.39.0
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - '0.0.0.0:9000:9000'
    restart: unless-stopped

  presence-detector:
    build:
      context: ../../
      dockerfile: Dockerfile
      target: dev # Use dev for when building on Main Desktop Machine
    container_name: presence-detector
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=1883
      - MQTT_CLIENT_ID=presence-detector
      - ROOM=master-bedroom
      - SENSOR_ID=1
      - PIN=C0
      - RUST_LOG=info
    networks:
      - IOT
    restart: unless-stopped
    privileged: true
networks:
  IOT:
    driver: bridge

volumes:
  portainer_data:
  mosquitto_data:
  mosquitto_log:
  node_red_data:
